### ISSUE TITLE
put this in all of the pages

### ISSUE THREAD

**Issue by pixlperfect01** [ComponentUp/componentup.github.io#2]
<p>add a button that links to it</p>

document.body.style.backgroundColor = sessionStorage.getItem("bg");
document.body.style.color = sessionStorage.getItem("cc");
function theme() {
    "rgb(255, 255, 255)" === sessionStorage.getItem("bg") ? (sessionStorage.setItem("bg", "rgb(6, 23, 37)"),
    sessionStorage.setItem("cc", "#777")) : null == sessionStorage.getItem("bg") ? (sessionStorage.setItem("bg", "rgb(6, 23, 37)"),
    sessionStorage.setItem("cc", "#777")) : "rgb(6, 23, 37)" === sessionStorage.getItem("bg") && (sessionStorage.setItem("bg", "rgb(255, 255, 255)"),
    sessionStorage.setItem("cc", "#333"));
    document.body.style.backgroundColor = sessionStorage.getItem("bg");
    document.body.style.color = sessionStorage.getItem("cc")
}

**Comment by pixlperfect01** [comment]
``

**Comment by leafjolt** [comment]
Is this the dark mode?

**Comment by leafjolt** [comment]
I used a different implementation of dark mode.
